name: Price Tracker

on:
  schedule:
    - cron: "0 * * * *"   # run every hour
  workflow_dispatch:

jobs:
  check_price:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TARGET_PRICE: ${{ secrets.TARGET_PRICE }}
          URL: ${{ secrets.URL }}
        run: python tracker.py
